prepare-cloud-image creates a portable image
liquidinvestigations/factory pull request #17
Opened 2017-10-07 19:28 UTC by mgax

Previously, the images inside the `images` folder contained baked-in
absolute paths, making them impossible to export and import into another
factory environment.

This patch cleans up the file handling of upstream cloud images and the
final qemu-related artifacts and fixes the baked-in path issue.

2017-10-09 10:19 UTC, gabriel-v requested changes

2017-10-09 10:19 UTC, gabriel-v commented on factory
> +DB_ROOT = Path.home() / '.factory'
So we're caching images in the user's home folder. It's a good default, but let's at least make it configurable.

Additionally, the readme should say that there's a cache in `~/.factory`.

2017-10-10 14:38 UTC, mgax commented
@gabriel-v I made the changes, now there's a `--db` option to `prepare-cloud-image`.

2017-10-10 19:22 UTC, gabriel-v approved these changes

2017-10-10 19:37 UTC, merged