Some improvements to run windows in a factory
liquidinvestigations/factory pull request #24
Opened 2017-11-19 21:32 UTC by mgax

* Connect an ISO file as cdrom (or two, because windows iso + virtio drivers iso)
* Simplify arm64 code (purely as side-effect, but it's so much cleaner now!)
* Connect to the serial console on stdio (which deactivates the whole connect-to-guest-via-ssh dance. windows has no ssh.)
* Create VNC server (because next next finish.)
* Save vm's disk as a new platform (useful when installing something by hand. like windows.)

2017-11-20 14:18 UTC, gabriel-v reviewed
arm64 build: 
`+ ./factory run true` gives out 
`RuntimeError: VM did not create its sockets`

see https://jenkins.liquiddemo.org/blue/organizations/jenkins/liquidinvestigations%2Ffactory/detail/PR-24/2/pipeline/30

2017-11-20 14:32 UTC, mgax commented
Yeah, that's weird, running that by hand works. Still digging.

2017-11-20 21:22 UTC, mgax commented
@gabriel-v I've rebased onto master and now it builds. I think the previous failure was a fluke.

2017-11-23 11:25 UTC, gabriel-v requested changes
Please add some auto-confirmation to `--commit` to make it scriptable.

2017-11-23 11:25 UTC, gabriel-v commented on Readme.md
> +* `--commit`: after the VM quits, save the changes to its disk.
You're saying this is interactive (asks for confirmation when the VM dies before overwriting). Where's the `-y` or `--always-commit` or something? Also, document it here.

2017-11-23 11:25 UTC, gabriel-v commented on factory.py
> +        subprocess.run(['socat', '-,cfmakeraw,escape=0xf', str(socket_path)])
I don't see `socat` listed as a dependency in the readme. Please add it.

2017-11-23 11:25 UTC, gabriel-v commented on factory.py
> +    parser.add_argument('-s', '--smp', default=1, type=int)
Sure, change them all you want, they're not used or documented anywhere anyway. I'd even say we'd be better off removing all the short options here.

2017-11-23 21:10 UTC, merged